/**
 * This file was auto-generated by Supabase. Do not edit this file directly.
 * Types for your database will be generated here using `supabase gen types typescript --local > types/database.ts`
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      ar_assessments: {
        Row: {
          ai_analysis_result: Json | null;
          ar_assessment_id: string | null;
          created_at: string;
          fal_ai_visualization_url: string | null;
          homeowner_id: string;
          id: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          ai_analysis_result?: Json | null;
          ar_assessment_id?: string | null;
          created_at?: string;
          fal_ai_visualization_url?: string | null;
          homeowner_id: string;
          id?: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          ai_analysis_result?: Json | null;
          ar_assessment_id?: string | null;
          created_at?: string;
          fal_ai_visualization_url?: string | null;
          homeowner_id?: string;
          id?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ar_assessments_homeowner_id_fkey";
            columns: ["homeowner_id"];
            isOneToOne: false;
            referencedRelation: "homeowner_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      contractor_profiles: {
        Row: {
          company_name: string | null;
          created_at: string;
          id: string;
          is_verified: boolean;
          license_number: string | null;
          phone_number: string | null;
          rating: number;
          service_areas: string[] | null;
          specialties: string[] | null;
          stripe_account_id: string | null;
          updated_at: string;
        };
        Insert: {
          company_name?: string | null;
          created_at?: string;
          id: string;
          is_verified?: boolean;
          license_number?: string | null;
          phone_number?: string | null;
          rating?: number;
          service_areas?: string[] | null;
          specialties?: string[] | null;
          stripe_account_id?: string | null;
          updated_at?: string;
        };
        Update: {
          company_name?: string | null;
          created_at?: string;
          id?: string;
          is_verified?: boolean;
          license_number?: string | null;
          phone_number?: string | null;
          rating?: number;
          service_areas?: string[] | null;
          specialties?: string[] | null;
          stripe_account_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contractor_profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      homeowner_profiles: {
        Row: {
          address: string | null;
          city: string | null;
          created_at: string;
          id: string;
          phone_number: string | null;
          state: string | null;
          updated_at: string;
          zip_code: string | null;
        };
        Insert: {
          address?: string | null;
          city?: string | null;
          created_at?: string;
          id: string;
          phone_number?: string | null;
          state?: string | null;
          updated_at?: string;
          zip_code?: string | null;
        };
        Update: {
          address?: string | null;
          city?: string | null;
          created_at?: string;
          id?: string;
          phone_number?: string | null;
          state?: string | null;
          updated_at?: string;
          zip_code?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "homeowner_profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      payments: {
        Row: {
          amount: number;
          created_at: string;
          currency: string;
          id: string;
          payee_id: string;
          payer_id: string;
          project_id: string;
          status: string;
          stripe_charge_id: string | null;
          payment_type: string | null;
          updated_at: string;
        };
        Insert: {
          amount: number;
          created_at?: string;
          currency?: string;
          id?: string;
          payee_id: string;
          payer_id: string;
          project_id: string;
          status?: string;
          stripe_charge_id?: string | null;
          payment_type?: string | null;
          updated_at?: string;
        };
        Update: {
          amount?: number;
          created_at?: string;
          currency?: string;
          id?: string;
          payee_id?: string;
          payer_id?: string;
          project_id?: string;
          status?: string;
          stripe_charge_id?: string | null;
          payment_type?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_payee_id_fkey";
            columns: ["payee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_payer_id_fkey";
            columns: ["payer_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          email: string;
          full_name: string | null;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          updated_at: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          email: string;
          full_name?: string | null;
          id: string;
          role?: Database["public"]["Enums"]["user_role"];
          updated_at?: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          email?: string;
          full_name?: string | null;
          id?: string;
          role?: Database["public"]["Enums"]["user_role"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      project_leads: {
        Row: {
          contractor_id: string;
          created_at: string;
          id: string;
          lead_cost: number;
          project_id: string;
          purchased_at: string | null;
          status: string;
          updated_at: string;
        };
        Insert: {
          contractor_id: string;
          created_at?: string;
          id?: string;
          lead_cost: number;
          project_id: string;
          purchased_at?: string | null;
          status?: string;
          updated_at?: string;
        };
        Update: {
          contractor_id?: string;
          created_at?: string;
          id?: string;
          lead_cost?: number;
          project_id?: string;
          purchased_at?: string | null;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "project_leads_contractor_id_fkey";
            columns: ["contractor_id"];
            isOneToOne: false;
            referencedRelation: "contractor_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "project_leads_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
        ];
      };
      projects: {
        Row: {
          ar_assessment_id: string | null;
          budget_estimate: number | null;
          created_at: string;
          description: string | null;
          end_date: string | null;
          homeowner_id: string;
          id: string;
          start_date: string | null;
          status: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          ar_assessment_id?: string | null;
          budget_estimate?: number | null;
          created_at?: string;
          description?: string | null;
          end_date?: string | null;
          homeowner_id: string;
          id?: string;
          start_date?: string | null;
          status?: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          ar_assessment_id?: string | null;
          budget_estimate?: number | null;
          created_at?: string;
          description?: string | null;
          end_date?: string | null;
          homeowner_id?: string;
          id?: string;
          start_date?: string | null;
          status?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "projects_ar_assessment_id_fkey";
            columns: ["ar_assessment_id"];
            isOneToOne: false;
            referencedRelation: "ar_assessments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_homeowner_id_fkey";
            columns: ["homeowner_id"];
            isOneToOne: false;
            referencedRelation: "homeowner_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      reviews: {
        Row: {
          comment: string | null;
          created_at: string;
          id: string;
          project_id: string;
          rating: number;
          reviewed_id: string;
          reviewer_id: string;
          updated_at: string;
        };
        Insert: {
          comment?: string | null;
          created_at?: string;
          id?: string;
          project_id: string;
          rating: number;
          reviewed_id: string;
          reviewer_id: string;
          updated_at?: string;
        };
        Update: {
          comment?: string | null;
          created_at?: string;
          id?: string;
          project_id?: string;
          rating?: number;
          reviewed_id?: string;
          reviewer_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_reviewed_id_fkey";
            columns: ["reviewed_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_reviewer_id_fkey";
            columns: ["reviewer_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_role: {
        Args: {};
        Returns: string;
      };
    };
    Enums: {
      user_role: "HOMEOWNER" | "CONTRACTOR" | "ADMIN";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
